"""SFJINZ — JednostkaInna (Annex 1 of the Accounting Act)."""

from app.services.schema_labels import SectionConfig, SchemaConfig, register_schema

TAG_LABELS: dict[str, str] = {
    # === BILANS - AKTYWA ===
    "Aktywa": "AKTYWA",
    "Aktywa_A": "A. Aktywa trwale",
    "Aktywa_A_I": "I. Wartosci niematerialne i prawne",
    "Aktywa_A_I_1": "1. Koszty zakonczonych prac rozwojowych",
    "Aktywa_A_I_2": "2. Wartosc firmy",
    "Aktywa_A_I_3": "3. Inne wartosci niematerialne i prawne",
    "Aktywa_A_I_4": "4. Zaliczki na wartosci niematerialne i prawne",
    "Aktywa_A_II": "II. Rzeczowe aktywa trwale",
    "Aktywa_A_II_1": "1. Srodki trwale",
    "Aktywa_A_II_1_A": "a) grunty (w tym prawo uzytkowania wieczystego gruntu)",
    "Aktywa_A_II_1_B": "b) budynki, lokale, prawa do lokali i obiekty inzynierii ladowej i wodnej",
    "Aktywa_A_II_1_C": "c) urzadzenia techniczne i maszyny",
    "Aktywa_A_II_1_D": "d) srodki transportu",
    "Aktywa_A_II_1_E": "e) inne srodki trwale",
    "Aktywa_A_II_2": "2. Srodki trwale w budowie",
    "Aktywa_A_II_3": "3. Zaliczki na srodki trwale w budowie",
    "Aktywa_A_III": "III. Naleznosci dlugoterminowe",
    "Aktywa_A_III_1": "1. Od jednostek powiazanych",
    "Aktywa_A_III_2": "2. Od pozostalych jednostek, w ktorych jednostka posiada zaangazowanie w kapitale",
    "Aktywa_A_III_3": "3. Od pozostalych jednostek",
    "Aktywa_A_IV": "IV. Inwestycje dlugoterminowe",
    "Aktywa_A_IV_1": "1. Nieruchomosci",
    "Aktywa_A_IV_2": "2. Wartosci niematerialne i prawne",
    "Aktywa_A_IV_3": "3. Dlugoterminowe aktywa finansowe",
    "Aktywa_A_IV_3_A": "a) w jednostkach powiazanych",
    "Aktywa_A_IV_3_A_1": "- udzialy lub akcje",
    "Aktywa_A_IV_3_A_2": "- inne papiery wartosciowe",
    "Aktywa_A_IV_3_A_3": "- udzielone pozyczki",
    "Aktywa_A_IV_3_A_4": "- inne dlugoterminowe aktywa finansowe",
    "Aktywa_A_IV_3_B": "b) w pozostalych jednostkach, w ktorych jednostka posiada zaangazowanie w kapitale",
    "Aktywa_A_IV_3_B_1": "- udzialy lub akcje",
    "Aktywa_A_IV_3_B_2": "- inne papiery wartosciowe",
    "Aktywa_A_IV_3_B_3": "- udzielone pozyczki",
    "Aktywa_A_IV_3_B_4": "- inne dlugoterminowe aktywa finansowe",
    "Aktywa_A_IV_3_C": "c) w pozostalych jednostkach",
    "Aktywa_A_IV_3_C_1": "- udzialy lub akcje",
    "Aktywa_A_IV_3_C_2": "- inne papiery wartosciowe",
    "Aktywa_A_IV_3_C_3": "- udzielone pozyczki",
    "Aktywa_A_IV_3_C_4": "- inne dlugoterminowe aktywa finansowe",
    "Aktywa_A_IV_4": "4. Inne inwestycje dlugoterminowe",
    "Aktywa_A_V": "V. Dlugoterminowe rozliczenia miedzyokresowe",
    "Aktywa_A_V_1": "1. Aktywa z tytulu odroczonego podatku dochodowego",
    "Aktywa_A_V_2": "2. Inne rozliczenia miedzyokresowe",
    "Aktywa_B": "B. Aktywa obrotowe",
    "Aktywa_B_I": "I. Zapasy",
    "Aktywa_B_I_1": "1. Materialy",
    "Aktywa_B_I_2": "2. Polprodukty i produkty w toku",
    "Aktywa_B_I_3": "3. Produkty gotowe",
    "Aktywa_B_I_4": "4. Towary",
    "Aktywa_B_I_5": "5. Zaliczki na dostawy i uslugi",
    "Aktywa_B_II": "II. Naleznosci krotkoterminowe",
    "Aktywa_B_II_1": "1. Naleznosci od jednostek powiazanych",
    "Aktywa_B_II_1_A": "a) z tytulu dostaw i uslug",
    "Aktywa_B_II_1_A_1": "- o okresie splaty do 12 miesiecy",
    "Aktywa_B_II_1_A_2": "- o okresie splaty powyzej 12 miesiecy",
    "Aktywa_B_II_1_B": "b) inne",
    "Aktywa_B_II_2": "2. Naleznosci od pozostalych jednostek, w ktorych jednostka posiada zaangazowanie w kapitale",
    "Aktywa_B_II_2_A": "a) z tytulu dostaw i uslug",
    "Aktywa_B_II_2_A_1": "- o okresie splaty do 12 miesiecy",
    "Aktywa_B_II_2_A_2": "- o okresie splaty powyzej 12 miesiecy",
    "Aktywa_B_II_2_B": "b) inne",
    "Aktywa_B_II_3": "3. Naleznosci od pozostalych jednostek",
    "Aktywa_B_II_3_A": "a) z tytulu dostaw i uslug",
    "Aktywa_B_II_3_A_1": "- o okresie splaty do 12 miesiecy",
    "Aktywa_B_II_3_A_2": "- o okresie splaty powyzej 12 miesiecy",
    "Aktywa_B_II_3_B": "b) z tytulu podatkow, dotacji, cel, ubezpieczen spolecznych i zdrowotnych oraz innych tyt. publicznoprawnych",
    "Aktywa_B_II_3_C": "c) inne",
    "Aktywa_B_II_3_D": "d) dochodzone na drodze sadowej",
    "Aktywa_B_III": "III. Inwestycje krotkoterminowe",
    "Aktywa_B_III_1": "1. Krotkoterminowe aktywa finansowe",
    "Aktywa_B_III_1_A": "a) w jednostkach powiazanych",
    "Aktywa_B_III_1_A_1": "- udzialy lub akcje",
    "Aktywa_B_III_1_A_2": "- inne papiery wartosciowe",
    "Aktywa_B_III_1_A_3": "- udzielone pozyczki",
    "Aktywa_B_III_1_A_4": "- inne krotkoterminowe aktywa finansowe",
    "Aktywa_B_III_1_B": "b) w pozostalych jednostkach",
    "Aktywa_B_III_1_B_1": "- udzialy lub akcje",
    "Aktywa_B_III_1_B_2": "- inne papiery wartosciowe",
    "Aktywa_B_III_1_B_3": "- udzielone pozyczki",
    "Aktywa_B_III_1_B_4": "- inne krotkoterminowe aktywa finansowe",
    "Aktywa_B_III_1_C": "c) srodki pieniezne i inne aktywa pieniezne",
    "Aktywa_B_III_1_C_1": "- srodki pieniezne w kasie i na rachunkach",
    "Aktywa_B_III_1_C_2": "- inne srodki pieniezne",
    "Aktywa_B_III_1_C_3": "- inne aktywa pieniezne",
    "Aktywa_B_III_2": "2. Inne inwestycje krotkoterminowe",
    "Aktywa_B_IV": "IV. Krotkoterminowe rozliczenia miedzyokresowe",
    "Aktywa_C": "C. Nalezne wplaty na kapital (fundusz) podstawowy",
    "Aktywa_D": "D. Udzialy (akcje) wlasne",

    # === BILANS - PASYWA ===
    "Pasywa": "PASYWA",
    "Pasywa_A": "A. Kapital (fundusz) wlasny",
    "Pasywa_A_I": "I. Kapital (fundusz) podstawowy",
    "Pasywa_A_II": "II. Kapital (fundusz) zapasowy, w tym nadwyzka wartosci sprzedazy nad wartoscia nominalna udzialow (akcji)",
    "Pasywa_A_II_1": "(w tym: nadwyzka wartosci sprzedazy nad nominalna)",
    "Pasywa_A_III": "III. Kapital (fundusz) z aktualizacji wyceny, w tym z tytulu trwalej utraty wartosci",
    "Pasywa_A_III_1": "(w tym: z tytulu trwalej utraty wartosci)",
    "Pasywa_A_IV": "IV. Pozostale kapitaly (fundusze) rezerwowe, w tym tworzone zgodnie z umowa (statutem) spolki",
    "Pasywa_A_IV_1": "(w tym: tworzone zgodnie z umowa spolki)",
    "Pasywa_A_IV_2": "(w tym: na udzialy (akcje) wlasne)",
    "Pasywa_A_V": "V. Zysk (strata) z lat ubieglych",
    "Pasywa_A_VI": "VI. Zysk (strata) netto",
    "Pasywa_A_VII": "VII. Odpisy z zysku netto w ciagu roku obrotowego (wartosc ujemna)",
    "Pasywa_B": "B. Zobowiazania i rezerwy na zobowiazania",
    "Pasywa_B_I": "I. Rezerwy na zobowiazania",
    "Pasywa_B_I_1": "1. Rezerwa z tytulu odroczonego podatku dochodowego",
    "Pasywa_B_I_2": "2. Rezerwa na swiadczenia emerytalne i podobne",
    "Pasywa_B_I_2_1": "a) dlugoterminowa",
    "Pasywa_B_I_2_2": "b) krotkoterminowa",
    "Pasywa_B_I_3": "3. Pozostale rezerwy",
    "Pasywa_B_I_3_1": "a) dlugoterminowe",
    "Pasywa_B_I_3_2": "b) krotkoterminowe",
    "Pasywa_B_II": "II. Zobowiazania dlugoterminowe",
    "Pasywa_B_II_1": "1. Wobec jednostek powiazanych",
    "Pasywa_B_II_2": "2. Wobec pozostalych jednostek, w ktorych jednostka posiada zaangazowanie w kapitale",
    "Pasywa_B_II_3": "3. Wobec pozostalych jednostek",
    "Pasywa_B_II_3_A": "a) kredyty i pozyczki",
    "Pasywa_B_II_3_B": "b) z tytulu emisji dluznych papierow wartosciowych",
    "Pasywa_B_II_3_C": "c) inne zobowiazania finansowe",
    "Pasywa_B_II_3_D": "d) zobowiazania wekslowe",
    "Pasywa_B_II_3_E": "e) inne",
    "Pasywa_B_III": "III. Zobowiazania krotkoterminowe",
    "Pasywa_B_III_1": "1. Zobowiazania wobec jednostek powiazanych",
    "Pasywa_B_III_1_A": "a) z tytulu dostaw i uslug",
    "Pasywa_B_III_1_A_1": "- o okresie wymagalnosci do 12 miesiecy",
    "Pasywa_B_III_1_A_2": "- o okresie wymagalnosci powyzej 12 miesiecy",
    "Pasywa_B_III_1_B": "b) inne",
    "Pasywa_B_III_2": "2. Zobowiazania wobec pozostalych jednostek, w ktorych jednostka posiada zaangazowanie w kapitale",
    "Pasywa_B_III_2_A": "a) z tytulu dostaw i uslug",
    "Pasywa_B_III_2_A_1": "- o okresie wymagalnosci do 12 miesiecy",
    "Pasywa_B_III_2_A_2": "- o okresie wymagalnosci powyzej 12 miesiecy",
    "Pasywa_B_III_2_B": "b) inne",
    "Pasywa_B_III_3": "3. Zobowiazania wobec pozostalych jednostek",
    "Pasywa_B_III_3_A": "a) kredyty i pozyczki",
    "Pasywa_B_III_3_B": "b) z tytulu emisji dluznych papierow wartosciowych",
    "Pasywa_B_III_3_C": "c) inne zobowiazania finansowe",
    "Pasywa_B_III_3_D": "d) z tytulu dostaw i uslug",
    "Pasywa_B_III_3_D_1": "- o okresie wymagalnosci do 12 miesiecy",
    "Pasywa_B_III_3_D_2": "- o okresie wymagalnosci powyzej 12 miesiecy",
    "Pasywa_B_III_3_E": "e) zaliczki otrzymane na dostawy i uslugi",
    "Pasywa_B_III_3_F": "f) zobowiazania wekslowe",
    "Pasywa_B_III_3_G": "g) z tytulu podatkow, cel, ubezpieczen spolecznych i zdrowotnych oraz innych tytul. publicznoprawnych",
    "Pasywa_B_III_3_H": "h) z tytulu wynagrodzen",
    "Pasywa_B_III_3_I": "i) inne",
    "Pasywa_B_III_4": "4. Fundusze specjalne",
    "Pasywa_B_IV": "IV. Rozliczenia miedzyokresowe",
    "Pasywa_B_IV_1": "1. Ujemna wartosc firmy",
    "Pasywa_B_IV_2": "2. Inne rozliczenia miedzyokresowe",
    "Pasywa_B_IV_2_1": "a) dlugoterminowe",
    "Pasywa_B_IV_2_2": "b) krotkoterminowe",

    # === RZiS POROWNAWCZY ===
    "A": "A. Przychody netto ze sprzedazy i zrownane z nimi",
    "A_J": "(w tym: od jednostek powiazanych)",
    "A_I": "I. Przychody netto ze sprzedazy produktow",
    "A_II": "II. Zmiana stanu produktow (zwiekszenie - wartosc dodatnia, zmniejszenie - wartosc ujemna)",
    "A_III": "III. Koszt wytworzenia produktow na wlasne potrzeby jednostki",
    "A_IV": "IV. Przychody netto ze sprzedazy towarow i materialow",
    "B": "B. Koszty dzialalnosci operacyjnej",
    "B_I": "I. Amortyzacja",
    "B_II": "II. Zuzycie materialow i energii",
    "B_III": "III. Uslugi obce",
    "B_IV": "IV. Podatki i oplaty, w tym podatek akcyzowy",
    "B_IV_1": "(w tym: podatek akcyzowy)",
    "B_V": "V. Wynagrodzenia",
    "B_VI": "VI. Ubezpieczenia spoleczne i inne swiadczenia, w tym emerytalne",
    "B_VI_1": "(w tym: emerytalne)",
    "B_VII": "VII. Pozostale koszty rodzajowe",
    "B_VIII": "VIII. Wartosc sprzedanych towarow i materialow",
    "C": "C. Zysk (strata) ze sprzedazy (A-B)",
    "D": "D. Pozostale przychody operacyjne",
    "D_I": "I. Zysk z tytulu rozchodu niefinansowych aktywow trwalych",
    "D_II": "II. Dotacje",
    "D_III": "III. Aktualizacja wartosci aktywow niefinansowych",
    "D_IV": "IV. Inne przychody operacyjne",
    "E": "E. Pozostale koszty operacyjne",
    "E_I": "I. Strata z tytulu rozchodu niefinansowych aktywow trwalych",
    "E_II": "II. Aktualizacja wartosci aktywow niefinansowych",
    "E_III": "III. Inne koszty operacyjne",
    "F": "F. Zysk (strata) z dzialalnosci operacyjnej (C+D-E)",
    "G": "G. Przychody finansowe",
    "G_I": "I. Dywidendy i udzialy w zyskach, w tym od jednostek powiazanych",
    "G_I_A": "a) od jednostek powiazanych",
    "G_I_A_1": "(w tym: w ktorych jednostka posiada zaangazowanie w kapitale)",
    "G_I_B": "b) od pozostalych jednostek",
    "G_I_B_1": "(w tym: w ktorych jednostka posiada zaangazowanie w kapitale)",
    "G_II": "II. Odsetki, w tym od jednostek powiazanych",
    "G_II_J": "(w tym: od jednostek powiazanych)",
    "G_III": "III. Zysk z tytulu rozchodu aktywow finansowych, w tym w jednostkach powiazanych",
    "G_III_J": "(w tym: w jednostkach powiazanych)",
    "G_IV": "IV. Aktualizacja wartosci aktywow finansowych",
    "G_V": "V. Inne",
    "H": "H. Koszty finansowe",
    "H_I": "I. Odsetki, w tym dla jednostek powiazanych",
    "H_I_J": "(w tym: dla jednostek powiazanych)",
    "H_II": "II. Strata z tytulu rozchodu aktywow finansowych, w tym w jednostkach powiazanych",
    "H_II_J": "(w tym: w jednostkach powiazanych)",
    "H_III": "III. Aktualizacja wartosci aktywow finansowych",
    "H_IV": "IV. Inne",
    "I": "I. Zysk (strata) brutto (F+G-H)",
    "J": "J. Podatek dochodowy",
    "K": "K. Pozostale obowiazkowe zmniejszenia zysku (zwiekszenia straty)",
    "L": "L. Zysk (strata) netto (I-J-K)",

    # === RACHUNEK PRZEPLYWOW PIENIEZNYCH (metoda posrednia) ===
    "CF.A_I": "I. Zysk (strata) netto",
    "CF.A_II": "II. Korekty razem",
    "CF.A_II_1": "1. Amortyzacja",
    "CF.A_II_2": "2. Zyski (straty) z tytulu roznic kursowych",
    "CF.A_II_3": "3. Odsetki i udzialy w zyskach (dywidendy)",
    "CF.A_II_4": "4. Zysk (strata) z dzialalnosci inwestycyjnej",
    "CF.A_II_5": "5. Zmiana stanu rezerw",
    "CF.A_II_6": "6. Zmiana stanu zapasow",
    "CF.A_II_7": "7. Zmiana stanu naleznosci",
    "CF.A_II_8": "8. Zmiana stanu zobowiazan krotkoterminowych (z wyjatkiem pozyczek i kredytow)",
    "CF.A_II_9": "9. Zmiana stanu rozliczen miedzyokresowych",
    "CF.A_II_10": "10. Inne korekty",
    "CF.A_III": "III. Przeplyw pieniezny netto z dzialalnosci operacyjnej (I +/- II)",
    "CF.B_I": "I. Wplywy",
    "CF.B_I_1": "1. Zbycie wartosci niematerialnych i prawnych oraz rzeczowych aktywow trwalych",
    "CF.B_I_2": "2. Zbycie inwestycji w nieruchomosci oraz wartosci niematerialne i prawne",
    "CF.B_I_3": "3. Z aktywow finansowych",
    "CF.B_I_3_A": "a) w jednostkach powiazanych",
    "CF.B_I_3_B": "b) w pozostalych jednostkach",
    "CF.B_I_3_B_1": "- zbycie aktywow finansowych",
    "CF.B_I_3_B_2": "- dywidendy i udzialy w zyskach",
    "CF.B_I_3_B_3": "- splata udzielonych pozyczek dlugoterminowych",
    "CF.B_I_3_B_4": "- odsetki",
    "CF.B_I_3_B_5": "- inne wplywy z aktywow finansowych",
    "CF.B_I_4": "4. Inne wplywy inwestycyjne",
    "CF.B_II": "II. Wydatki",
    "CF.B_II_1": "1. Nabycie wartosci niematerialnych i prawnych oraz rzeczowych aktywow trwalych",
    "CF.B_II_2": "2. Inwestycje w nieruchomosci oraz wartosci niematerialne i prawne",
    "CF.B_II_3": "3. Na aktywa finansowe",
    "CF.B_II_4": "4. Inne wydatki inwestycyjne",
    "CF.B_III": "III. Przeplyw pieniezny netto z dzialalnosci inwestycyjnej (I-II)",
    "CF.C_I": "I. Wplywy",
    "CF.C_I_1": "1. Wplywy netto z wydania udzialow i innych instrumentow kapitalowych oraz doplat do kapitalu",
    "CF.C_I_2": "2. Kredyty i pozyczki",
    "CF.C_I_3": "3. Emisja dluznych papierow wartosciowych",
    "CF.C_I_4": "4. Inne wplywy finansowe",
    "CF.C_II": "II. Wydatki",
    "CF.C_II_1": "1. Nabycie udzialow (akcji) wlasnych",
    "CF.C_II_2": "2. Dywidendy i inne wyplaty na rzecz wlascicieli",
    "CF.C_II_3": "3. Inne niz wyplaty na rzecz wlascicieli wydatki z tytulu podzialu zysku",
    "CF.C_II_4": "4. Splaty kredytow i pozyczek",
    "CF.C_II_5": "5. Wykup dluznych papierow wartosciowych",
    "CF.C_II_6": "6. Z tytulu innych zobowiazan finansowych",
    "CF.C_II_7": "7. Platnosci zobowiazan z tytulu umow leasingu finansowego",
    "CF.C_II_8": "8. Odsetki",
    "CF.C_II_9": "9. Inne wydatki finansowe",
    "CF.C_III": "III. Przeplyw pieniezny netto z dzialalnosci finansowej (I-II)",
    "CF.D": "D. Przeplyw pieniezny netto razem (A.III +/- B.III +/- C.III)",
    "CF.E": "E. Bilansowa zmiana stanu srodkow pienieznych, w tym",
    "CF.E_1": "(w tym: zmiana stanu srodkow pienieznych z tytulu roznic kursowych)",
    "CF.F": "F. Srodki pieniezne na poczatek okresu",
    "CF.G": "G. Srodki pieniezne na koniec okresu (F +/- D), w tym",
    "CF.G_1": "(w tym: o ograniczonej mozliwosci dysponowania)",
}

SECTIONS: SectionConfig = {
    "bilans_element": "Bilans",
    "aktywa_element": "Aktywa",
    "pasywa_element": "Pasywa",
    "rzis_element": "RZiS",
    "rzis_has_variants": True,
    "cf_element": "RachPrzeplywow",
    "cf_has_variants": True,
    "unit_multiplier": 1,
    "extra_sections": [
        {"element": "ZestZmianWKapitale", "store_as": "equity_changes", "tag_prefix": "EQ."},
    ],
}

CONFIG: SchemaConfig = {
    "code": "SFJINZ",
    "root_tags": [
        "JednostkaInna",
        "SprFinJednostkaInnaWZlotych",
        "JednostkaInnaWTys",
        "SprFinJednostkaInnaWTysiacach",
    ],
    "sections": SECTIONS,
    "tag_labels": TAG_LABELS,
    "statement_markers": ["Bilans", "RZiS", "RachPrzeplywow"],
}

register_schema(CONFIG)
