"""SFJMAZ — JednostkaMala (Annex 5 of the Accounting Act)."""

from app.services.schema_labels import SectionConfig, SchemaConfig, register_schema

TAG_LABELS: dict[str, str] = {
    # === BILANS - AKTYWA (BilansJednostkaMala) ===
    "Aktywa": "AKTYWA",
    "Aktywa_A": "A. Aktywa trwale",
    "Aktywa_A_I": "I. Wartosci niematerialne i prawne",
    "Aktywa_A_II": "II. Rzeczowe aktywa trwale",
    "Aktywa_A_II_1": "1. Srodki trwale",
    "Aktywa_A_II_2": "2. Srodki trwale w budowie",
    "Aktywa_A_III": "III. Naleznosci dlugoterminowe",
    "Aktywa_A_IV": "IV. Inwestycje dlugoterminowe, w tym:",
    "Aktywa_A_IV_1": "1. nieruchomosci",
    "Aktywa_A_IV_2": "2. dlugoterminowe aktywa finansowe",
    "Aktywa_A_V": "V. Dlugoterminowe rozliczenia miedzyokresowe",
    "Aktywa_B": "B. Aktywa obrotowe",
    "Aktywa_B_I": "I. Zapasy",
    "Aktywa_B_II": "II. Naleznosci krotkoterminowe, w tym:",
    "Aktywa_B_II_A": "a) z tytulu dostaw i uslug",
    "Aktywa_B_II_A_1": "- do 12 miesiecy",
    "Aktywa_B_II_A_2": "- powyzej 12 miesiecy",
    "Aktywa_B_III": "III. Inwestycje krotkoterminowe, w tym:",
    "Aktywa_B_III_A": "a) krotkoterminowe aktywa finansowe, w tym:",
    "Aktywa_B_III_A_1": "- srodki pieniezne w kasie i na rachunkach",
    "Aktywa_B_IV": "IV. Krotkoterminowe rozliczenia miedzyokresowe",
    "Aktywa_C": "C. Nalezne wplaty na kapital (fundusz) podstawowy",
    "Aktywa_D": "D. Udzialy (akcje) wlasne",

    # === BILANS - PASYWA ===
    "Pasywa": "PASYWA",
    "Pasywa_A": "A. Kapital (fundusz) wlasny",
    "Pasywa_A_I": "I. Kapital (fundusz) podstawowy",
    "Pasywa_A_II": "II. Kapital (fundusz) zapasowy, w tym:",
    "Pasywa_A_II_1": "(w tym: nadwyzka wartosci sprzedazy nad nominalna)",
    "Pasywa_A_III": "III. Kapital (fundusz) z aktualizacji wyceny, w tym:",
    "Pasywa_A_III_1": "(w tym: z tytulu trwalej utraty wartosci)",
    "Pasywa_A_IV": "IV. Pozostale kapitaly (fundusze) rezerwowe",
    "Pasywa_A_V": "V. Zysk (strata) z lat ubieglych",
    "Pasywa_A_VI": "VI. Zysk (strata) netto",
    "Pasywa_A_VII": "VII. Odpisy z zysku netto w ciagu roku obrotowego (wartosc ujemna)",
    "Pasywa_B": "B. Zobowiazania i rezerwy na zobowiazania",
    "Pasywa_B_I": "I. Rezerwy na zobowiazania, w tym:",
    "Pasywa_B_I_1": "(w tym: rezerwa z tytulu odroczonego podatku dochodowego)",
    "Pasywa_B_II": "II. Zobowiazania dlugoterminowe, w tym:",
    "Pasywa_B_II_1": "(w tym: z tytulu kredytow i pozyczek)",
    "Pasywa_B_III": "III. Zobowiazania krotkoterminowe, w tym:",
    "Pasywa_B_III_A": "a) z tytulu kredytow i pozyczek",
    "Pasywa_B_III_B": "b) z tytulu dostaw i uslug",
    "Pasywa_B_III_B_1": "- do 12 miesiecy",
    "Pasywa_B_III_B_2": "- powyzej 12 miesiecy",
    "Pasywa_B_III_C": "c) fundusze specjalne",
    "Pasywa_B_IV": "IV. Rozliczenia miedzyokresowe",

    # === RZiS POROWNAWCZY (under RZiSJednostkaMala > RZiSPor) ===
    "A": "A. Przychody netto ze sprzedazy i zrownane z nimi",
    "A_I": "I. Przychody netto ze sprzedazy produktow",
    "A_II": "II. Zmiana stanu produktow (zwiekszenie +, zmniejszenie -)",
    "A_III": "III. Koszt wytworzenia produktow na wlasne potrzeby jednostki",
    "B": "B. Koszty dzialalnosci operacyjnej",
    "B_I": "I. Amortyzacja",
    "B_II": "II. Zuzycie materialow i energii",
    "B_III": "III. Uslugi obce",
    "B_IV": "IV. Podatki i oplaty",
    "B_V": "V. Wynagrodzenia",
    "B_V_1": "(w tym: wynagrodzenia z zysku)",
    "B_VI": "VI. Ubezpieczenia spoleczne i inne swiadczenia",
    "B_VI_1": "(w tym: emerytalne)",
    "C": "C. Zysk (strata) ze sprzedazy (A-B)",
    "D": "D. Pozostale przychody operacyjne, w tym:",
    "D_1": "(w tym: aktualizacja wartosci aktywow niefinansowych)",
    "E": "E. Pozostale koszty operacyjne, w tym:",
    "E_1": "(w tym: aktualizacja wartosci aktywow niefinansowych)",
    "F": "F. Przychody finansowe",
    "F_I": "I. Dywidendy i udzialy w zyskach, w tym:",
    "F_I_1": "(w tym: od jednostek powiazanych)",
    "F_II": "II. Odsetki, w tym:",
    "F_II_1": "(w tym: od jednostek powiazanych)",
    "F_III": "III. Zysk z tytulu rozchodu aktywow finansowych, w tym:",
    "F_III_1": "(w tym: w jednostkach powiazanych)",
    "F_IV": "IV. Aktualizacja wartosci aktywow finansowych",
    "G": "G. Koszty finansowe",
    "G_I": "I. Odsetki, w tym:",
    "G_I_1": "(w tym: dla jednostek powiazanych)",
    "G_II": "II. Strata z tytulu rozchodu aktywow finansowych, w tym:",
    "G_II_1": "(w tym: w jednostkach powiazanych)",
    "G_III": "III. Aktualizacja wartosci aktywow finansowych",
    "H": "H. Zysk (strata) brutto (C+D-E+F-G)",
    "I": "I. Podatek dochodowy",
    "J": "J. Zysk (strata) netto (H-I)",
}

SECTIONS: SectionConfig = {
    "bilans_element": "BilansJednostkaMala",
    "aktywa_element": "Aktywa",
    "pasywa_element": "Pasywa",
    "rzis_element": "RZiSJednostkaMala",
    "rzis_has_variants": True,
    "cf_element": None,
    "cf_has_variants": False,
    "unit_multiplier": 1,
    "extra_sections": [],
}

CONFIG: SchemaConfig = {
    "code": "SFJMAZ",
    "root_tags": [
        "JednostkaMala",
        "SprFinJednostkaMalaWZlotych",
        "JednostkaMalaWTys",
        "SprFinJednostkaMalaWTysiacach",
    ],
    "sections": SECTIONS,
    "tag_labels": TAG_LABELS,
    "statement_markers": ["BilansJednostkaMala", "RZiSJednostkaMala"],
}

register_schema(CONFIG)
