"""SFZURT — ZakladUbezpieczen (Annex 3 of the Accounting Act).

Insurance/reinsurance companies.  Amounts in the XML are in thousands of PLN
(WTysiacach), so unit_multiplier=1000 normalises to PLN at parse time.
"""

from app.services.schema_labels import SectionConfig, SchemaConfig, register_schema

TAG_LABELS: dict[str, str] = {
    # === BILANS - AKTYWA (BilansZakladUbezpieczen) ===
    "Aktywa": "AKTYWA",
    "Aktywa_A": "A. Wartosc firmy",
    "Aktywa_A_1": "1. wartosc firmy - Loss given default",
    "Aktywa_A_2": "2. inne wartosci niematerialne i prawne",
    "Aktywa_B": "B. Wartosci niematerialne i prawne",
    "Aktywa_B_I": "I. Koszty prac rozwojowych",
    "Aktywa_B_I_1": "1. koszty prac rozwojowych - oprogramowanie",
    "Aktywa_B_I_2": "2. koszty prac rozwojowych - pozostale",
    "Aktywa_B_I_3": "3. zaliczki na wartosci niematerialne i prawne",
    "Aktywa_B_II": "II. Inne wartosci niematerialne i prawne",
    "Aktywa_B_II_1": "1. oprogramowanie",
    "Aktywa_B_II_2": "2. inne",
    "Aktywa_B_II_3": "3. zaliczki na wartosci niematerialne i prawne",
    "Aktywa_B_III": "III. Rzeczowe aktywa trwale",
    "Aktywa_B_III_1": "1. grunty wlasne i prawo uzytkowania wieczystego gruntu",
    "Aktywa_B_III_2": "2. budynki i budowle",
    "Aktywa_B_III_3": "3. urzadzenia techniczne i maszyny",
    "Aktywa_B_III_4": "4. srodki transportu",
    "Aktywa_B_III_5": "5. pozostale srodki trwale",
    "Aktywa_B_III_6": "6. srodki trwale w budowie i zaliczki na srodki trwale",
    "Aktywa_B_III_7": "7. inne",
    "Aktywa_B_IV": "IV. Prawo do uzytkowania skladnika aktywow",
    "Aktywa_C": "C. Udzial reasekuratorow w rezerwach techniczno-ubezpieczeniowych",
    "Aktywa_D": "D. Lokaty (inwestycje)",
    "Aktywa_D_I": "I. Nieruchomosci",
    "Aktywa_D_I_1": "1. grunty wlasne i prawo uzytkowania wieczystego gruntu",
    "Aktywa_D_I_1_1": "a) grunty wlasne uzywane na wlasne potrzeby",
    "Aktywa_D_I_1_2": "b) pozostale grunty wlasne",
    "Aktywa_D_I_2": "2. budynki i budowle",
    "Aktywa_D_I_2_1": "a) budynki i budowle uzywane na wlasne potrzeby",
    "Aktywa_D_I_2_2": "b) pozostale budynki i budowle",
    "Aktywa_D_I_3": "3. inwestycje budowlane i zaliczki",
    "Aktywa_D_I_3_1": "a) inwestycje budowlane",
    "Aktywa_D_I_3_2": "b) zaliczki na poczet inwestycji budowlanych",
    "Aktywa_D_II": "II. Lokaty w jednostkach powiazanych",
    "Aktywa_D_II_1": "1. udzialy, akcje i inne papiery wartosciowe o zmiennej kwocie dochodu",
    "Aktywa_D_II_2": "2. dluzne papiery wartosciowe i inne papiery wartosciowe o stalej kwocie dochodu",
    "Aktywa_D_III": "III. Inne lokaty finansowe",
    "Aktywa_D_III_1": "1. udzialy, akcje i inne papiery wartosciowe o zmiennej kwocie dochodu",
    "Aktywa_D_III_2": "2. dluzne papiery wartosciowe i inne papiery wartosciowe o stalej kwocie dochodu",
    "Aktywa_D_III_2_1": "a) obligacje i inne dluzne papiery wartosciowe",
    "Aktywa_D_III_2_2": "b) udzialy w funduszach wspolnego inwestowania o stalym dochodzie",
    "Aktywa_E": "E. Naleznosci",
    "Aktywa_E_I": "I. Naleznosci z tytulu ubezpieczen bezposrednich",
    "Aktywa_E_II": "II. Naleznosci z tytulu reasekuracji",
    "Aktywa_E_III": "III. Inne naleznosci",
    "Aktywa_F": "F. Pozostale aktywa",
    "Aktywa_F_I": "I. Rzeczowe aktywa trwale, inne niz nieruchomosci",
    "Aktywa_F_II": "II. Srodki pieniezne",
    "Aktywa_F_III": "III. Pozostale aktywa",
    "Aktywa_F_IV": "IV. Kapital pozyczkowy pozaskladkowy",
    "Aktywa_G": "G. Rozliczenia miedzyokresowe",
    "Aktywa_H": "H. Aktywa z tytulu odroczonego podatku dochodowego",

    # === BILANS - PASYWA ===
    "Pasywa": "PASYWA",
    "Pasywa_A": "A. Kapital wlasny",
    "Pasywa_A_I": "I. Kapital podstawowy",
    "Pasywa_A_II": "II. Kapital zapasowy",
    "Pasywa_A_III": "III. Kapital z aktualizacji wyceny",
    "Pasywa_A_IV": "IV. Pozostale kapitaly rezerwowe",
    "Pasywa_A_V": "V. Niepodzielony wynik z lat ubieglych",
    "Pasywa_A_VI": "VI. Wynik netto roku obrotowego",
    "Pasywa_A_VII": "VII. Odpisy z zysku netto w ciagu roku obrotowego (wartosc ujemna)",
    "Pasywa_B": "B. Zobowiazania podporzadkowane",
    "Pasywa_C": "C. Rezerwy techniczno-ubezpieczeniowe",
    "Pasywa_C_I": "I. Rezerwa skladek i rezerwa na ryzyko niewygasle",
    "Pasywa_C_II": "II. Rezerwa na niewypowiedziane okresy ubezpieczen",
    "Pasywa_C_III": "III. Rezerwa ubezpieczen na zycie",
    "Pasywa_C_IV": "IV. Rezerwy na niewyptacone odszkodowania i swiadczenia",
    "Pasywa_C_V": "V. Rezerwy na premie i rabaty dla ubezpieczajacych",
    "Pasywa_C_VI": "VI. Rezerwy na wyrownanie szkodowosci (ryzyk)",
    "Pasywa_C_VII": "VII. Pozostale rezerwy techniczno-ubezpieczeniowe",
    "Pasywa_C_VIII": "VIII. Rezerwy techniczno-ubezpieczeniowe na udzial wlasny",
    "Pasywa_D": "D. Rezerwy techniczno-ubezpieczeniowe (zycie, ryzyko lokaty ponosi ubezpieczajacy)",
    "Pasywa_D_I": "I. Rezerwa ubezpieczen na zycie",
    "Pasywa_D_II": "II. Rezerwa skladek",
    "Pasywa_D_III": "III. Rezerwy na niewyptacone odszkodowania i swiadczenia",
    "Pasywa_D_IV": "IV. Rezerwy na premie i rabaty dla ubezpieczajacych",
    "Pasywa_D_V": "V. Pozostale rezerwy techniczno-ubezpieczeniowe",
    "Pasywa_D_VI": "VI. Rezerwy techniczno-ubezpieczeniowe na udzial wlasny",
    "Pasywa_E": "E. Pozostale rezerwy",
    "Pasywa_E_1": "1. rezerwa z tytulu odroczonego podatku dochodowego",
    "Pasywa_E_2": "2. pozostale rezerwy",
    "Pasywa_F": "F. Zobowiazania z tytulu depozytow reasekuratorow",
    "Pasywa_F_I": "I. Zobowiazania z tytulu ubezpieczen bezposrednich",
    "Pasywa_F_II": "II. Zobowiazania z tytulu reasekuracji",
    "Pasywa_F_III": "III. Pozostale zobowiazania",
    "Pasywa_G": "G. Rozliczenia miedzyokresowe i przychody przyszlych okresow",
    "Pasywa_H": "H. Zobowiazania (bez pozycji F)",
    "Pasywa_H_I": "I. Zobowiazania dlugoterminowe",
    "Pasywa_H_II": "II. Zobowiazania krotkoterminowe",
    "Pasywa_H_III": "III. Rozliczenia miedzyokresowe",
    "Pasywa_I": "I. Rozliczenia miedzyokresowe i przychody przyszlych okresow",

    # === RZiS (RZiSZakladUbezpieczen — Roman numeral top-level items) ===
    "I": "I. Skladki przypisane brutto",
    "II": "II. Przychody z lokat (inwestycji)",
    "II_1": "1. przychody z lokat w jednostkach powiazanych",
    "II_2": "2. przychody z pozostalych lokat",
    "II_2_1": "a) przychody z nieruchomosci",
    "II_2_2": "b) przychody z pozostalych lokat",
    "II_2_3": "c) wynik dodatni z realizacji lokat",
    "II_3": "3. niezrealizowane zyski z lokat",
    "II_4": "4. wynik dodatni z tytulu roznic kursowych",
    "II_5": "5. pozostale przychody z lokat",
    "III": "III. Odszkodowania i swiadczenia wyplacone brutto",
    "IV": "IV. Zmiana stanu rezerw techniczno-ubezpieczeniowych na udzial wlasny",
    "V": "V. Koszty dzialalnosci ubezpieczeniowej",
    "V_1": "1. koszty akwizycji",
    "V_2": "2. koszty administracyjne",
    "V_3": "3. prowizje reasekuracyjne i udzialy w zyskach reasekuratorow",
    "V_4": "4. pozostale koszty techniczne na udzial wlasny",
    "VI": "VI. Przychody z lokat netto przeniesione z/do technicznego rachunku ubezpieczen",
    "VII": "VII. Wynik techniczny (I-III+/-IV-V+/-VI)",
    "VIII": "VIII. Przychody z lokat netto przeniesione z technicznego rachunku ubezpieczen",
    "IX": "IX. Pozostale przychody operacyjne",
    "X": "X. Pozostale koszty operacyjne",
    "XI": "XI. Zysk (strata) z dzialalnosci operacyjnej",
    "XII": "XII. Przychody nadzwyczajne",
    "XIII": "XIII. Koszty nadzwyczajne",
    "XIV": "XIV. Zysk (strata) brutto",
    "XV": "XV. Podatek dochodowy",
    "XVI": "XVI. Pozostale obowiazkowe zmniejszenia zysku (zwiekszenia straty)",

    # === RACHUNEK PRZEPLYWOW PIENIEZNYCH (PrzeplywyZakladUbezpieczen) ===
    "CF.A": "A. Przeplywy z dzialalnosci operacyjnej",
    "CF.A_I": "I. Wplywy",
    "CF.A_I_1": "1. Skladki brutto otrzymane",
    "CF.A_I_2": "2. Przychody z lokat",
    "CF.A_I_3": "3. Pozostale wplywy operacyjne",
    "CF.A_II": "II. Wydatki",
    "CF.A_II_1": "1. Odszkodowania i swiadczenia wyplacone",
    "CF.A_II_2": "2. Wydatki na lokaty",
    "CF.A_II_3": "3. Podatek dochodowy zaplacony",
    "CF.A_III": "III. Przeplywy pieniezne netto z dzialalnosci operacyjnej (I-II)",
    "CF.B": "B. Przeplywy z dzialalnosci inwestycyjnej",
    "CF.B_I": "I. Wplywy",
    "CF.B_I_1": "1. Zbycie nieruchomosci",
    "CF.B_I_2": "2. Zbycie udzialow, akcji i innych papierow wartosciowych",
    "CF.B_I_3": "3. Realizacja dluznych papierow wartosciowych",
    "CF.B_I_4": "4. Zbycie udzialow lub akcji w jednostkach powiazanych",
    "CF.B_I_5": "5. Udzielone pozyczki (wplywy ze splat)",
    "CF.B_I_6": "6. Zbycie lokaty terminowej",
    "CF.B_I_7": "7. Lokaty - inne wplywy",
    "CF.B_II": "II. Wydatki",
    "CF.B_II_1": "1. Nabycie nieruchomosci",
    "CF.B_II_2": "2. Nabycie udzialow, akcji i innych papierow wartosciowych",
    "CF.B_II_3": "3. Nabycie dluznych papierow wartosciowych",
    "CF.B_II_4": "4. Nabycie udzialow lub akcji w jednostkach powiazanych",
    "CF.B_II_5": "5. Udzielone pozyczki (wydatki)",
    "CF.B_II_6": "6. Nabycie lokaty terminowej",
    "CF.B_II_7": "7. Lokaty - inne wydatki",
    "CF.B_II_8": "8. Nabycie rzeczowych aktywow trwalych",
    "CF.B_II_9": "9. Nabycie wartosci niematerialnych i prawnych",
    "CF.B_III": "III. Przeplywy pieniezne netto z dzialalnosci inwestycyjnej (I-II)",
    "CF.C": "C. Przeplywy z dzialalnosci finansowej",
    "CF.C_I": "I. Wplywy",
    "CF.C_I_1": "1. Wplywy z emisji akcji wlasnych",
    "CF.C_I_2": "2. Wplywy z kredytow i pozyczek",
    "CF.C_I_3": "3. Inne wplywy finansowe",
    "CF.C_II": "II. Wydatki",
    "CF.C_II_1": "1. Wyplata dywidend",
    "CF.C_II_2": "2. Splata kredytow i pozyczek",
    "CF.C_II_3": "3. Odsetki zaplacone",
    "CF.C_II_4": "4. Nabycie akcji wlasnych",
    "CF.C_II_5": "5. Platnosci zobowiazan z tytulu leasingu",
    "CF.C_II_6": "6. Inne wydatki finansowe",
    "CF.C_III": "III. Przeplywy pieniezne netto z dzialalnosci finansowej (I-II)",
    "CF.D": "D. Przeplywy pieniezne netto razem (A.III+/-B.III+/-C.III)",
    "CF.E": "E. Bilansowa zmiana stanu srodkow pienieznych",
    "CF.E_1": "(w tym: zmiana stanu srodkow pienieznych z tytulu roznic kursowych)",
    "CF.F": "F. Srodki pieniezne na poczatek okresu",
    "CF.G": "G. Srodki pieniezne na koniec okresu (F+/-D)",
    "CF.G_1": "(w tym: o ograniczonej mozliwosci dysponowania)",
}

SECTIONS: SectionConfig = {
    "bilans_element": "BilansZakladUbezpieczen",
    "aktywa_element": "Aktywa",
    "pasywa_element": "Pasywa",
    "rzis_element": "RZiSZakladUbezpieczen",
    "rzis_has_variants": False,
    "cf_element": "PrzeplywyZakladUbezpieczen",
    "cf_has_variants": False,
    "unit_multiplier": 1000,
    "extra_sections": [
        {"element": "PozabilansoweZakladUbezpieczen", "store_as": "off_balance_sheet", "tag_prefix": "OBS."},
    ],
}

CONFIG: SchemaConfig = {
    "code": "SFZURT",
    "root_tags": [
        "ZakladUbezpieczenWTys",
        "SprFinZakladUbezpieczenWTysiacach",
        "ZakladUbezpieczenWZlotych",
        "SprFinZakladUbezpieczenWZlotych",
        "ZakladUbezpieczen",
    ],
    "sections": SECTIONS,
    "tag_labels": TAG_LABELS,
    "statement_markers": [
        "BilansZakladUbezpieczen",
        "RZiSZakladUbezpieczen",
        "PrzeplywyZakladUbezpieczen",
    ],
}

register_schema(CONFIG)
